version: '3.9'

services:

  postgres:
    image: postgres:16

    container_name: coreflow-postgres

    restart: always

    environment:
      POSTGRES_DB: coreflow
      POSTGRES_USER: isluc
      POSTGRES_PASSWORD: 1604

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: