spring.application.name=core-flow

spring.datasource.url=jdbc:postgresql://localhost:5432/coreflow
spring.datasource.username=isluc
spring.datasource.password=1604

spring.jpa.hibernate.ddl-auto=update

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

server.port=8080